global:
  sendAnonymousUsage: false

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik
    watch: true

api:
  insecure: true

serversTransport:
  insecureSkipVerify: true

entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ':443'

  websocket:
    address: ':24678'

tls:
  certificates:
    - certFile: /etc/certs/cert.pem
      keyFile: /etc/certs/key.pem
  stores:
    default:
      defaultCertificate:
        certFile: /etc/certs/cert.pem
        keyFile: /etc/certs/key.pem

ping:
  entryPoint: 'web'

log:
  level: INFO